# 공통설정
server:
  port: 8080

#http://localhost:8080/h2-console
spring:
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        show_sql: false
        ddl-auto: create-drop
        id:
          new_generator_mappings: false
      hbm2ddl:
        auto: none

# 로그레벨의 설정  쿼리 및 결과의 로그 출력 레벨 조정이 가능
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
#    com.bs.search: INFO

logging:
  level:
    com.bs.search: INFO


# log설정
log:
  pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%X{identity}] %msg %n"
  appender: console

book-api:
  uri: "https://dapi.kakao.com/v3/search/book"
api:
    head: Authorization
    auth: KakaoAK
    key: KakaoAK 8c65087a8ceb9dafcbcaefbd5bff3599
    uri: https://dapi.kakao.com/v3/search/book?target=title

