# 공통설정
server:
  port: 8080


spring:
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    username: sa
#    : 스프링부트 2.4부터는 spring.datasource.username=sa 를 꼭 추가해주어야 한다. 그렇지 않으면 오류 발생생
    password:
  jpa:
   properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        show_sql: false
        ddl-auto: create-drop
#        hibernate.default_batch_fetch_size: 1000
#        entity 를 바탕으로 테이블 직접생성 기능
        id:
          new_generator_mappings: false
      hbm2ddl:
        auto: none
  security:
    oauth2:
      client:
        registration:
          google :
            client-id: 345365462651-cv5lp2m1kr48gb1hpc5o0bis9mrqjq7p.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          kakao:
            authorization-grant-type: authorization_code
            client-id: 8c65087a8ceb9dafcbcaefbd5bff3599
            client-secret: umFQ9mtUnf1UBgoP7oVjB646lDSmF9dt
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - account_email
            client-authentication-method: POST
            client-name: Kakao

        provider:

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    com.bs.search: info

log:
  pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%X{identity}] %msg %n"
  appender: console

book-api:
  uri: "https://dapi.kakeo.com/v3/search/book"
api:
  key: KakaoAK 8c65087a8ceb9dafcbcaefbd5bff3599
  uri: https://dapi.kakao.com/v3/search/book?target=title

